name: style-fix
on: [push]
jobs:
  style-fix:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2, cs2pr

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Execute style fix
        run: |
          vendor/bin/php-cs-fixer fix || true
          vendor/bin/phpcbf || true

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "bot@github.actions"
      - name: commit
        run: |
          git add -u
          (git commit -m ":art: Auto style fix" && git push origin) || true
